

tagline: Site Tagline
author :
  name : Mohammed O. Tillawy
  email : tillawy@gmail.com
  github : wehighlight
  twitter : wehighlight

name: "WeHighlight.com"
description: "WeHighlight About Public Site"

url: "about.wehighlight.com"

gems: [jekyll-paginate, jekyll-gist]


paginate: 10

markdown: kramdown

