

tagline: Site Tagline
author :
  name : Mohammed O. Tillawy
  email : tillawy@gmail.com
  github : hilitit
  twitter : hiliit

name: "Hilit.it"
description: "Hilit.it Public Site"

url: "www.hilit.it"

paginate: 10

markdown: kramdown

